name: Create GitHub Release for WorkerAnalysisGUI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller (One-Folder mode)
        # 요청하신 명령어를 기반으로, 안정성을 위해 hidden-import 옵션을 추가했습니다.
        run: pyinstaller --name "WorkerAnalysisGUI" --onedir --windowed --icon="assets/logo.ico" --add-data "assets;assets" --add-data "config;config" --hidden-import pandas --hidden-import tkcalendar --hidden-import watchdog.observers --hidden-import matplotlib --hidden-import Pillow WorkerAnalysisGUI.py

      - name: Zip the build folder
        # 빌드된 폴더 전체(dist/WorkerAnalysisGUI)를 압축합니다.
        run: |
          Compress-Archive -Path dist/WorkerAnalysisGUI -DestinationPath "WorkerAnalysisGUI-${{ github.ref_name }}.zip"
      
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: "WorkerAnalysisGUI-${{ github.ref_name }}.zip"
          name: "Release ${{ github.ref_name }}"
          body: "New release version ${{ github.ref_name }}"
          draft: false
          prerelease: false